"""
Formats the final report into multiple output formats.
"""

from datetime import UTC, datetime

import prompts
from pipeline.processor import AnalysisResult


def _iso(dt: datetime | None) -> str | None:
    return dt.isoformat() if dt else None


class ReportFormatter:
    def to_markdown(self, report_text: str, result: AnalysisResult) -> str:
        now = datetime.now(UTC).isoformat().replace("+00:00", "Z")
        header = (
            f"# LogLens Incident Report\n\n"
            f"- **generated_at:** {now}\n"
            f"- **log_source:** {result.log_source.value}\n"
            f"- **lines_analysed:** {result.total_lines}\n"
            f"- **prompt_version:** {prompts.VERSION}\n\n"
        )
        footer = f"\n\n---\nGenerated by LogLens v{prompts.VERSION}"
        return header + report_text.strip() + footer

    def to_json(self, report_text: str, result: AnalysisResult) -> dict:
        md = self.to_markdown(report_text, result)
        severity = self.infer_severity(result)
        return {
            "ok": True,
            "metadata": {
                "generated_at": datetime.now(UTC).isoformat().replace("+00:00", "Z"),
                "log_source": result.log_source.value,
                "total_lines": result.total_lines,
                "prompt_version": prompts.VERSION,
            },
            "severity": severity,
            "summary": {
                "error_rate": result.error_rate,
                "warning_rate": result.warning_rate,
                "critical_count": result.critical_count,
                "time_range": [_iso(result.time_range[0]), _iso(result.time_range[1])],
                "processing_time_ms": result.processing_time_ms,
            },
            "root_causes": [
                {
                    "hypothesis": r.hypothesis,
                    "confidence": r.confidence,
                    "evidence": r.evidence,
                    "category": r.category,
                    "first_signal_at": _iso(r.first_signal_at),
                    "recommended_actions": r.recommended_actions,
                }
                for r in result.root_causes
            ],
            "anomalies": [
                {
                    "timestamp": _iso(a.timestamp),
                    "anomaly_type": a.anomaly_type,
                    "severity": a.severity,
                    "description": a.description,
                    "affected_lines": a.affected_lines,
                    "z_score": a.z_score,
                    "baseline_value": a.baseline_value,
                    "observed_value": a.observed_value,
                }
                for a in result.anomalies
            ],
            "error_clusters": [
                {
                    "cluster_id": c.cluster_id,
                    "representative_message": c.representative_message,
                    "count": c.count,
                    "first_seen": _iso(c.first_seen),
                    "last_seen": _iso(c.last_seen),
                    "severity": c.severity,
                    "sample_messages": c.sample_messages,
                    "affected_services": c.affected_services,
                }
                for c in result.error_clusters
            ],
            "timeline": [
                {
                    "timestamp": _iso(t.timestamp),
                    "event_type": t.event_type,
                    "description": t.description,
                    "severity": t.severity,
                    "related_entries": t.related_entries,
                }
                for t in result.timeline
            ],
            "incident_report_markdown": md,
        }

    def infer_severity(self, result: AnalysisResult) -> str:
        high_conf = any(
            r.confidence == "high" for r in result.root_causes
        )
        if result.critical_count > 0 and high_conf:
            return "P1"
        cascade = any(a.anomaly_type == "cascade_failure" for a in result.anomalies)
        if result.error_rate > 0.1 or cascade:
            return "P2"
        if result.error_rate > 0.02 or len(result.anomalies) > 0:
            return "P3"
        return "P4"
